project_id = "hzttqloyamcivctsfxkk"

[functions.generate-module]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.gemini-image]
verify_jwt = false

[functions.gemini-stream]
verify_jwt = false

[functions.execute-prompt]
verify_jwt = false